-- MySQL Script generated by MySQL Workbench
-- Sat Dec 10 13:37:32 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`activite_horaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`activite_horaire` ;

CREATE TABLE IF NOT EXISTS `mydb`.`activite_horaire` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `marche_code` TINYINT(3) UNSIGNED ZEROFILL NOT NULL,
  `marche_label` VARCHAR(20) NOT NULL,
  `jour_date` DATE NOT NULL,
  `jour_libelle` ENUM('lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche') NOT NULL,
  `heure_debut` TIME NOT NULL,
  `heure_fin` TIME NOT NULL COMMENT '	',
  `poid_ca` DECIMAL(5,2) NOT NULL,
  `tickets_nb` TINYINT UNSIGNED NOT NULL,
  `panier_moyen` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_horaire` (`heure_debut` ASC, `heure_fin` ASC),
  INDEX `idx_marche` (`marche_code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entree_jour`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`entree_jour` ;

CREATE TABLE IF NOT EXISTS `mydb`.`entree_jour` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `total` INT NULL,
  `galerie_sud_percent` DECIMAL(5,2) UNSIGNED NULL,
  `galerie_sud_quantite` INT UNSIGNED NULL,
  `porte_parking_percent` DECIMAL(5,2) UNSIGNED NULL,
  `porte_parking_quantite` INT UNSIGNED NULL,
  `galerie_nord_percent` DECIMAL(5,2) UNSIGNED NULL,
  `galerie_nord_quantite` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_date` (`date` ASC),
  INDEX `idx_date_lieu` (`date` ASC, `galerie_sud_quantite` ASC, `porte_parking_quantite` ASC, `galerie_nord_quantite` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evenement_sportif`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`evenement_sportif` ;

CREATE TABLE IF NOT EXISTS `mydb`.`evenement_sportif` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_debut` DATE NOT NULL,
  `date_fin` DATE NOT NULL,
  `type` VARCHAR(45) NULL,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evenement_meteo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`evenement_meteo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`evenement_meteo` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `type` TINYINT(1) NULL,
  `label` TINYINT(1) NULL,
  `pluie` TINYINT(1) NULL,
  `neige` TINYINT(1) NULL,
  `soleil` TINYINT(1) NULL,
  `vent` TINYINT(1) NULL,
  `temperature` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evenement_divers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`evenement_divers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`evenement_divers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_debut` DATE NOT NULL,
  `date_fin` DATE NOT NULL,
  `type` VARCHAR(45) NULL,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
